### ISSUE TITLE
Can't find way to get Uri

### ISSUE THREAD

**Issue by Globinnjaliath** [LucasPJS/on_audio_query#10]
Thanks for making this amazing plugin. How can I get uri of an item from songlist?

**Comment by LucasPJS** [comment]
You can use `[data]` from `[SongModel]`. Will return something like `//storage/folderName/songName.mp3`

**Comment by Globinnjaliath** [comment]
Thanks for the quick reply. Unfortunately that's not the one am looking for, I want to get something like this content//media/external/audio/media/932 instead of filepath.
Thank you...

**Comment by LucasPJS** [comment]
I know, actually I was thinking about adding others URI types, but, never found a good reason.

 I'll add more types of URI for songs files.

**Comment by Globinnjaliath** [comment]
Okay thanks...
