### ISSUE TITLE
Add ArtworkType.Artist in queryArtWorks()

### ISSUE THREAD

**Issue by SxzOtaku** [LucasPJS/on_audio_query#13]
Can you add fetching the artwork via ArtworkType.Artist and its artist id?

**Comment by LucasPJS** [comment]
As far i know, the only image inside a audio file is the cover. However, android query don't let you extract this image(if exists).

**Comment by SxzOtaku** [comment]
hmmm...  instead of fetching the actual artist image how about fetching the cover art using the ArtworkType.Artist and its artist id? what do you think? is it good?

**Comment by LucasPJS** [comment]
You want to get the song image using artist id? I don't get you point.

**Comment by SxzOtaku** [comment]
sorry I just got mixed up with a probably dead package I'm currently on.
