### ISSUE TITLE
Not working in release mode... 

### ISSUE THREAD

**Issue by Globinnjaliath** [LucasPJS/on_audio_query#14]
I think I have messed up with something. The app is working fine in debug mode, but not release mode. Storage request permission also not showing in release mode. I have tried with Android 10 & 11 both not working. Any help?
Thank you..

**Comment by LucasPJS** [comment]
Fixed?

**Comment by Globinnjaliath** [comment]
Yes.. Thank you...

**Comment by sam0829** [comment]
@Globinnjaliath It would be helpful if you can also post the solution here :)
