### ISSUE TITLE
Can't request more methods

### ISSUE THREAD

**Issue by Globinnjaliath** [LucasPJS/on_audio_query#15]
I tried to call methods `querySongs`, `queryAlbums`, `queryArtists` from 1 page at a time and throws an error. When I tried from separate pages its working. Is this error expected? Is there any way to call all from same page?

**Comment by LucasPJS** [comment]
What type of error?

**Comment by Globinnjaliath** [comment]
I was getting something related to storage permission. I found a way by calling method 1 by 1. Thanks for your time.
