### ISSUE TITLE
OnAudioQuery().queryAudiosFrom(AudiosFromType.GENRE_NAME,genre); is returning no songs in Android 11.

### ISSUE THREAD

**Issue by shaan-mephobic** [LucasPJS/on_audio_query#16]
I've tried `on_audio_query: 1.1.1` and `on_audio_query: 1.1.0` and its returning all songs of the genres. But, `on_audio_query: 1.1.2` isn't returning songs. I saw that you made changes in GENRES on that . I'm aware that the app crashes on lower android versions on older versions of the package. So I guess android version is upto it again. Will you please take a look into it ?

**Comment by LucasPJS** [comment]
There's something on log? Or just don't load the songs?

**Comment by shaan-mephobic** [comment]
No, there is no logs. It doesn't load the songs.

**Comment by shaan-mephobic** [comment]
That was fast! Thank you :)
