### ISSUE TITLE
Fetching songs/audios from specific folders

### ISSUE THREAD

**Issue by Globinnjaliath** [LucasPJS/on_audio_query#17]
Is there any way can fetch songs/audios from specific folders? Or option to blacklist some folders?

**Comment by LucasPJS** [comment]
>Is there any way can fetch songs/audios from specific folders?

You can use `queryFromFolder`. `queryAllPath` will return all possible path.

**Comment by Globinnjaliath** [comment]
Thank you. I got it `queryFromFolder`. But is there any way to list audios only from specific folders when I request for query all audios?

**Comment by LucasPJS** [comment]
Unfortunately no, i'll add this has a new feature. Soon will be a method for this.

**Comment by LucasPJS** [comment]
For now i've added a `path` parameter to `querySongs` and `queryAudios`, this will fetch only songs/audios with the same path. Later i'll think about something more advanced.
