### ISSUE TITLE
QueryArtwork for album's art returning null in latest version

### ISSUE THREAD

**Issue by shaan-mephobic** [LucasPJS/on_audio_query#21]
Here's the version that I'm using,
`on_audio_query: ^2.0.0`

This is the code I used,
`await OnAudioQuery().queryArtwork(
          allAlbums[i].id, ArtworkType.ALBUM,
          format: ArtworkFormat.JPEG, size: 350);`

Works fine in `  on_audio_query: ^1.1.3+1`

edit: worth mentioning that song's artwork is working fine. Only album's artwork is returning null.

**Comment by LucasPJS** [comment]
Hey @shaan-mephobic, i tested and everything works fine. What is your Android version?

**Comment by shaan-mephobic** [comment]
Mine is Android 11. I tested it again in `on_audio_query: 2.1.1` and it's returning null.
