### ISSUE TITLE
Remove song from playlist

### ISSUE THREAD

**Issue by FadiChaalab** [LucasPJS/on_audio_query#22]
Adding a song to the playlist works fine but removing a song fails.
Could you assign someone to this task? , thanks in advance.

**Comment by LucasPJS** [comment]
Could you provide more information? Android or IOS? Plugin version, Android version and if was any log from terminal?

**Comment by FadiChaalab** [comment]
Am using android as os, for version of android it's 6.0.0,  for plugin version it's the last one which is 2.0.0 and for debug output no error thrown.
