### ISSUE TITLE
search type audio

### ISSUE THREAD

**Issue by g0coders** [LucasPJS/on_audio_query#26]
hai @LucasPJS, how to take audio from mp3 type, how do you do it?

**Comment by LucasPJS** [comment]
I don't understand what you want but, If you like to `play` the mp3 file. Use [just_audio](https://pub.dev/packages/just_audio) or [audioplayers](https://pub.dev/packages/audioplayers)(More simple) plugins.

This plugin you can **only** get audios available device storage.
