### ISSUE TITLE
iOS Error OnArtworkQuery.swift　

### ISSUE THREAD

**Issue by hndrr** [LucasPJS/on_audio_query#37]
Build passes on Android, but on iOS, `OnArtworkQuery.swift` throws errors, so the build does not pass.
"2.3.1" is being used.

The following is the error message
```
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/hndr/.pub-cache/hosted/pub.dartlang.org/on_audio_query-2.3.1/ios/Classes/query/OnArtworkQuery.swift:58:35: error: type 'MPMediaQuery' has no member 'artist'
                cursor = MPMediaQuery.artist()
                         ~~~~~~~~~~~~ ^~~~~~
    /Users/hndr/.pub-cache/hosted/pub.dartlang.org/on_audio_query-2.3.1/ios/Classes/query/OnArtworkQuery.swift:103:125: error: cannot convert value of type 'Double' to expected argument type 'CGFloat'
                    tempArtwork = tempItem?.artwork?.image(at: CGSize(width: size, height: size))?.jpegData(compressionQuality: fixedQuality)
```

The first error disappeared when I fixed it to `MPMediaQuery.artists()`, but I didn't know how to deal with the second error because I am not familiar with Swift.
Finally, thank you for publishing a great package.

**Comment by LucasPJS** [comment]
I made some changes but i couldn't test so, if don't work, you can tell me.
