### ISSUE TITLE
Error in OnArtworkQuery.swift again, Build does not pass on iOS

### ISSUE THREAD

**Issue by hndrr** [LucasPJS/on_audio_query#38]
Thank you for the quick fix. https://github.com/LucasPJS/on_audio_query/issues/37

I have changed the version to `2.4.0.` However, another error is preventing Build from going through.

```
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/hndr/.pub-cache/hosted/pub.dartlang.org/on_audio_query-2.4.0/ios/Classes/query/OnArtworkQuery.swift:66:40: error: variable 'filter' used before being initialized
                cursor?.addFilterPredicate(filter)
                                           ^
    /Users/hndr/.pub-cache/hosted/pub.dartlang.org/on_audio_query-2.4.0/ios/Classes/query/OnArtworkQuery.swift:39:13: note: variable defined here
            var filter: MPMediaPropertyPredicate
                ^
```

I'm testing it in the repository here.  https://github.com/hndrr/audio_query_sample

**Comment by hndrr** [comment]
I'm not sure if this is correct, but I commented it out and the build went through.

<img width="1088" alt="スクリーンショット 2021-09-29 20 18 41" src="https://user-images.githubusercontent.com/53109993/135258918-7aa71728-38be-44fb-a441-823d6566efcb.png">

**Comment by LucasPJS** [comment]
Probably because i forgot to define the filter as a possible null value.

https://github.com/LucasPJS/on_audio_query/blob/8d560c44d692e3e36a90b58ef34815ace0367a16/on_audio_query/ios/Classes/query/OnArtworkQuery.swift#L39

This time i'll do in a different way, if there's no problem to you. To avoid multiples 'releases' and futures bugs. Try using the development version.

```yaml
on_audio_query:
  git:
    url: git://github.com/LucasPJS/on_audio_query.git
    ref: development
```

If everything works fine, i'll update the official version with the fix.

**Comment by hndrr** [comment]
@LucasPJS 
Thank you very much. But I still seem to get an Error.
And It wouldn't drop unless I specified a path.
```
  on_audio_query:
    git:
      url: git://github.com/LucasPJS/on_audio_query.git
      ref: development
      path: on_audio_query/
```

```
    ** BUILD FAILED **
Xcode's output:
    Command CompileSwift failed with a nonzero exit code
    /Users/hndr/.pub-cache/git/on_audio_query-3d41db6ab033f7be1a20adc5e4688b66b5a8a2d6/on_audio_query/ios/Classes/query/OnArtworkQuery.swift:65:40: error: value of optional type 'MPMediaPropertyPredicate?' must be unwrapped to a value of type 'MPMediaPropertyPredicate'
                cursor?.addFilterPredicate(filter)
                                           ^
    /Users/hndr/.pub-cache/git/on_audio_query-3d41db6ab033f7be1a20adc5e4688b66b5a8a2d6/on_audio_query/ios/Classes/query/OnArtworkQuery.swift:65:40: note: coalesce using '??' to provide a default when the optional value contains 'nil'
                cursor?.addFilterPredicate(filter)
                                           ^
                                                  ?? <#default value#>
```

**Comment by LucasPJS** [comment]
@hndrr. Could you try again? Use `flutter pub get` to get the newest changes. I'm sorry but, i can't do this debug right now.

**Comment by hndrr** [comment]
@LucasPJS 
Yes, sir. It was just the same as the Error content above.
The notes are a little different, but I think the error keeps coming up in the same place.

**Comment by hndrr** [comment]
@LucasPJS 
I applied this manually, and Build is now passing.
Thank you very much. 🙇‍♂️

https://github.com/LucasPJS/on_audio_query/pull/40/commits/038f4a5c9a7d3ff3f6d01b025c85eaf76c3385bb

**Comment by LucasPJS** [comment]
Oh, nice!. I'll prepare my iphone and do more tests to make sure that there's no others bugs before releasing the update.
