### ISSUE TITLE
All album arts rebuild again after state changes in app when using QueryArtworkWidget()

### ISSUE THREAD

**Issue by shaan-mephobic** [LucasPJS/on_audio_query#6]
Hey first of all, this is by far the best and easy dependency I found. Thanks for your hard work :)
As the title suggests I have a small bug with the album arts. I also came across other plugins having the same issue. Here is [one](https://github.com/ryanheise/audio_service/issues/667). To make the listview faster I use cacheextent and that makes all the album arts blackout for a second or two . Can you please do something for this?

**Comment by LucasPJS** [comment]
Hi!, Thanks for usig this plugin. 

I did several tests to avoid bugs like this but never tried using `[cacheextent]`. In theory, it shouldn't happen this blackout in any artwork. I'll do more tests and see what I can do.

**Comment by shaan-mephobic** [comment]
It would be cool if you could add **_nullArtworkWidget_** for **OnAudioQuery().queryArtworks()** just like  **QueryArtworkWidget()** has :)

**Comment by LucasPJS** [comment]
I already thought about it, but, using one unique image could not be good to everyone. `[QueryArtworkWidget]` it's just a example on how to get images on Android 10 or above. 

When calling `[queryArtworks]` if album/audio don't has a image, will return null. In this case you should use a `if case` and adding your own image.

About this issue, I still need do some tests, but querying image using Bitmap/Uint8List it's slow and could cause this "blackout". Using app debbuing mode you'll see a super slow performace and a lot of lagging but, as you can see [here](https://user-images.githubusercontent.com/76869974/112378123-522c1a00-8cc5-11eb-880d-ba67706c415d.gif), release mode handle a lot better.

I think the performance could be better but, i still don't know how to do that. It's one of the item in my [TODO](https://github.com/LucasPJS/on_audio_query#todo).

**Comment by shaan-mephobic** [comment]
**QueryArtworks** doesn't actually return anything if there is no art. Can you please confirm with that?

**Comment by LucasPJS** [comment]
The method will always has 0 as a value.

> [OnArtworksQuery.kt#L54](https://github.com/LucasPJS/on_audio_query/blob/b7e7e75f17e8b7fa81f776e3c3029c085280a000/android/src/main/kotlin/com/lucasjosino/on_audio_query/query/OnArtworksQuery.kt#L54)
```kotlin
var artData = ByteArray(0)
```

Before return to Dart, if there's no art (Value still 0), the plugin will return nothing(null).
> [OnArtworksQuery.kt#L41-L48](https://github.com/LucasPJS/on_audio_query/blob/b7e7e75f17e8b7fa81f776e3c3029c085280a000/android/src/main/kotlin/com/lucasjosino/on_audio_query/query/OnArtworksQuery.kt#L41-L48)
```kotlin
//Query everything in the Background it's necessary for better performance
viewModelScope.launch {
    //Start querying
    val resultArtList: ByteArray = loadArt()

    //Flutter UI will start, but, information still loading
    if (resultArtList.isNotEmpty()) result.success(resultArtList)
}
```

After this you will need check if the method returned with a value or no.
> [queryArtworkWidget.dart#L40-L50](https://github.com/LucasPJS/on_audio_query/blob/b7e7e75f17e8b7fa81f776e3c3029c085280a000/lib/widget/queryArtworkWidget.dart#L40-L50)
```Dart
if (item.data != null) {
    return ClipRRect(
      borderRadius: artworkBorder ?? BorderRadius.circular(50),
      child: Image.memory(
        item.data!,
        width: artworkWidth ?? 50,
        height: artworkHeight ?? 50,
        fit: artworkFit ?? BoxFit.cover,
        filterQuality: artworkQuality ?? FilterQuality.low,
      ),
    );
}
```

**Comment by LucasPJS** [comment]
I did some tests and everything works fine in both `[debug]` and `[release]` mode.

Tested on version ^1.0.6 and on Android 10.

**Comment by shaan-mephobic** [comment]
Here is the code I'm working with 

```
ListView.builder(
      padding: EdgeInsets.only(top: 5, bottom: 8),
      addAutomaticKeepAlives: true,
      itemExtent: deviceWidth / 6,
      // cacheExtent: (songList.length * 2.0),
      physics: BouncingScrollPhysics(),
      itemCount: songList.length,
      itemBuilder: (context, index) {
        return ListTile(
          onTap: () async {
            await play_this(index);
          },
          dense: false,
          enabled: true,
          title: Text(
            songList[index].title,
            style: TextStyle(
              color: Colors.white70,
              fontFamily: 'UrbanR',
              shadows: [
                Shadow(
                  offset: Offset(1.0, 1.0),
                  blurRadius: 3.0,
                  color: Colors.black54,
                ),
              ],
            ),
          ),
          tileColor: Colors.transparent,
          subtitle: Text(
            songList[index].artist,
            style: TextStyle(
              color: Colors.white38,
              shadows: [
                Shadow(
                  offset: Offset(1.0, 1.0),
                  blurRadius: 2.0,
                  color: Colors.black45,
                ),
              ],
            ),
          ),
          trailing: Icon(Icons.more_vert_rounded, color: Colors.white12),
          leading:
              AnimatedContainer(
            duration: Duration(milliseconds: 500),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(3),
              boxShadow: [
                BoxShadow(
                  color: Colors.black26,
                  blurRadius: 5.0,
                  spreadRadius: deviceWidth / 140,
                ),
              ],
            ),
            child: QueryArtworkWidget(
                id: songList[index].id,
                type: ArtworkType.AUDIO,
                nullArtworkWidget: Container(
                  child: Icon(
                    Icons.album_rounded,
                    size: deviceWidth / 10,
                  ),
                ),
                artworkBorder: BorderRadius.circular(3),
                artworkFit: BoxFit.cover),
          ),
        );
      },
    );
```


https://user-images.githubusercontent.com/66886966/118674908-c8598280-b817-11eb-8987-4571133013d8.mp4

As you can see the in the above video, the album arts keep rebuilding since I'm using a seekbar which causes the app's state to change constantly.

I didn't use `cacheextent` and I'm in `release` mode.

`on_audio_query: ^1.0.6` tested in android 11.

I found this closed issue that's pretty much related to the same [problem](https://github.com/flutter/flutter/issues/22514)

**Comment by LucasPJS** [comment]
Okay, now i can understand what's going on.

So, `[QueryArtworkWidget]` use `[FutureBuilder]` and everytime flutter state changes `[FutureBuilder]` will "update" too.

> Before - [Emulator - Pixel 4 - Android 11 - Debug] (Using normal example & QueryArtworkWidget)

https://user-images.githubusercontent.com/76869974/118709335-36d81980-b7f3-11eb-9fce-6f8fa270a554.mp4

> After - [Emulator - Pixel 4 - Android 11 - Debug] (Using `[queryArtwork()]` method)

https://user-images.githubusercontent.com/76869974/118709770-ca114f00-b7f3-11eb-847d-f6a39e9d090f.mp4

The major problem is: `[QueryArtworkWidget]` uses both `[FutureBuilder]` and `[queryArtwork()]`. FutureBuilder will always reload when flutter state change and will call queryArtwork method which return a `[Uint8List]`(Slow) for each audio.

The second video it's almost a solution, but, cost a lot of time and work. Instead of loading both querySongs and queryArtwork using FutureBuilder i loaded everything in `[initState]` and added to a `[List<SongModel>]` and `[List<Uint8List>]`. This will avoid multiples calls from FutureBuilder(No more load). But, takes 2 - 4 seconds to load ~ 600 songs (Tested on a real device - Debug, I forgot to test in release mode, i think will take 1 - 2 seconds).

Maybe, if i add a method to load all Artwork without using Dart thread will work.

**Comment by shaan-mephobic** [comment]
>   late List<SongModel> songList;
>   late List<Uint8List> artList;
> 
>   @override
>   void initState() {
>     super.initState();
>     getSongsAndArtwork();
>   }
> 
>   getSongsAndArtwork() async {
>     songList = await OnAudioQuery().querySongs();
> 
>   songList.forEach((element) async {
>       artList.add(
>           await OnAudioQuery().queryArtworks(element.id, ArtworkType.AUDIO));
>     });
>   }

This code is super fast and seems to fix the state problem but it doesn't place the correct album art for the correct song, it gets shuffled. I tried using `for loop` instead of `foreach loop` but it exits the loop after it tries to read the album art of a song that doesn't have one.
 `OnAudioQuery().queryArtworks()` doesn't return null for songs that doesn't have album art. 

Even in the second video you sent has shuffled the album arts.

**Comment by LucasPJS** [comment]
And, if you try adding a if case?

> Not tested

```dart
  late List<SongModel> songList;
  late List<Uint8List> artList;

  @override
  void initState() {
    super.initState();
    getSongsAndArtwork();
  }

  getSongsAndArtwork() async {
    songList = await OnAudioQuery().querySongs();

    songList.forEach((element) async {
      Uint8List uArt = await OnAudioQuery().queryArtworks(element.id, ArtworkType.AUDIO));
      uArt != null ? artList.add({uArt}) : artList.add({null})
  }
```

I don't know if adding `[null]` will work, if not, you can try add a empty string `[""]`: 

```dart
    songList.forEach((element) async {
      Uint8List uArt = await OnAudioQuery().queryArtworks(element.id, ArtworkType.AUDIO));
      uArt != null ? artList.add({uArt}) : artList.add({""})
  }
```

And when adding the artwork you can use 

```dart
    if (artList[SomeIndex].isNotEmpty()) {
      //isNotEmpty() it's used in Kotlin, i don't remember if exist in Dart
      //Add artwork
    } else {
      //Add "Non Artwork" image
    }
```

**Comment by shaan-mephobic** [comment]
I tried these but it gave me the same results. Maybe if there was a way to identify if a song has an album art I can fix this problem by using.

```
if(song.hasArt){
    artsList.add(await OnAudioQuery().queryArtworks(songList[i].id, ArtworkType.AUDIO)));
}
else{
  artList.add(someotherimage);
}
```

**Comment by LucasPJS** [comment]
> OnAudioQuery().queryArtworks() doesn't return null for songs that doesn't have album art.

Yeah, my bad.

```kotlin
//Query everything in the Background it's necessary for better performance
viewModelScope.launch {
    //Start querying
    val resultArtList: ByteArray = loadArt()

    //Flutter UI will start, but, information still loading
    if (resultArtList.isNotEmpty()) result.success(resultArtList)
}

```

This part don't prevent null artwork and will always send a value(Not the artwork).

I'll fix this and upload a new version.

**Comment by LucasPJS** [comment]
Hey, @shaan-mephobic. The new version is out. Update to version ^1.0.8

See more [CHANGELOG](https://github.com/LucasPJS/on_audio_query/blob/main/CHANGELOG.md) 

I added `[keepOldArtwork]` to `[QueryArtworkWidget]`. This will keep the artwork even when Flutter State change.

**Comment by shaan-mephobic** [comment]
Wow! I tried both the methods and both of them work. Thank you for your amazing work and support :)
