### ISSUE TITLE
there a difference between the artistId of AlbumModel and the id of ArtistModel?

### ISSUE THREAD

**Issue by hndrr** [LucasPJS/on_audio_query#60]
there a difference between the ArtistID of AlbumModel and the ID of ArtistModel?

I have debugged it in iOS environment, but they are not the same value.
So I am using the Artist name for filtering, but it may cause some inconvenience.

**Comment by LucasPJS** [comment]
Actually, yes. After reviewing the code i noticed that i'm using `AlbumArtistPersistentID` instead of `ArtistPersistentID`. And the id sometimes are too big so, flutter return a wrong int.

I'll fix this issue.
