### ISSUE TITLE
Apple Music filePath reference becomes null

### ISSUE THREAD

**Issue by hndrr** [LucasPJS/on_audio_query#61]
If you have an Apple Music subscription on iOS, the Apple Music file will be detected, but you will not be able to play it because the file reference will be null.

Is there any other way to determine if the file is an Apple Music file or not other than by checking if it is null?

I wanted to hide artists and albums that I couldn't play, but I didn't know how to do that, so I checked if the filePath of the song was null and filtered Album and Artist.

**Comment by LucasPJS** [comment]
> Is there any other way to determine if the file is an Apple Music file or not other than by checking if it is null?

I added a filter to avoid this Cloud files since you can't play them but, i couldn't test.
I'll see what is going on.

https://github.com/LucasPJS/on_audio_query/blob/cc3cdd8166390caff8e71e7ee71aad90db64e867/on_audio_query/ios/Classes/query/OnAudioQuery.swift#L26-L30

**Comment by hndrr** [comment]
Thank you very much. It will be very helpful if it is resolved.

**Comment by LucasPJS** [comment]
There's no 'native' method to check if the artist or album is from Cloud but, i added more checks. Unfortunately i couldn't test to see the result.
