### ISSUE TITLE
Method to get genre of a song.

### ISSUE THREAD

**Issue by shaan-mephobic** [LucasPJS/on_audio_query#9]
Hi! I used  `OnAudioQuery().queryGenres();` to get all the genres that are available but I want to show each song of those specific genre, and I couldn't find a method to get the genre of a song. Can you please help me with this?

**Comment by LucasPJS** [comment]
There's the method `[queryAudiosFrom]`.

But, I never had a change to made a real test of this method.

> Example:

```dart
// You can use the [AudiosFromType.GENRE_NAME] or [AudiosFromType.GENRE_ID].
List<SongModel> genreSongs = await OnAudioQuery().queryAudiosFrom(AudiosFromType.GENRE_NAME, genreName); 
```

**Comment by shaan-mephobic** [comment]
Really sorry to not do my research properly before creating an issue. This method works as intended in real device too. Hope you have a fantastic day :)
